# Generated by Django 2.2.3 on 2019-07-06 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('closed', 'Closed')], default='new', max_length=16, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='chats.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='announcement', serialize=False, to='democracy.DiscussionTopic', verbose_name='Topic')),
                ('announcement_description', models.TextField(verbose_name='Announcement description')),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='initiative', serialize=False, to='democracy.DiscussionTopic', verbose_name='Topic')),
                ('problem_description', models.TextField(verbose_name='Problem description')),
                ('solution_description', models.TextField(verbose_name='Solution description')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_col', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('status', models.CharField(choices=[('new', 'New'), ('complete', 'Complete')], default='new', max_length=16, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Step name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='democracy.Initiative', verbose_name='Initiative')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.PositiveIntegerField(default=3, verbose_name='Relevance')),
                ('vote', models.NullBooleanField(default=None, verbose_name='Vote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='democracy.Initiative', verbose_name='Initiative')),
            ],
            options={
                'unique_together': {('user', 'initiative')},
            },
        ),
    ]
