# Generated by Django 2.2.3 on 2019-07-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='alert',
            field=models.BooleanField(default=False, verbose_name='Is alert'),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('voting', 'Voting'), ('closed', 'Closed')], default='new', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='initiativefeedback',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='democracy.Initiative', verbose_name='Initiative'),
        ),
    ]
