# Generated by Django 2.2.3 on 2019-07-06 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0002_auto_20190706_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='democracy.AdvertisementCategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='ads_images')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('range', models.PositiveIntegerField(default=0, verbose_name='Range')),
                ('is_paid', models.BooleanField(verbose_name='Is paid')),
                ('paid_period', models.PositiveIntegerField(default=0, verbose_name='Paid period')),
                ('order_col', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='democracy.AdvertisementSubcategory', verbose_name='Subcategory')),
            ],
        ),
    ]
