# Generated by Django 2.2.3 on 2019-07-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0003_advertisement_advertisementcategory_advertisementsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='order_col',
        ),
        migrations.AddField(
            model_name='advertisementcategory',
            name='order_col',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='advertisementsubcategory',
            name='order_col',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
