# Generated by Django 2.2.3 on 2019-07-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0004_auto_20190706_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discussion_images'),
        ),
    ]
